"""Deterministic derived plans, elevations, sections, schedules, and SVG output."""

from .generator import (
    ElevationSpec,
    LabelProvider,
    PlanSpec,
    SectionSpec,
    Symbol,
    SymbolProvider,
    VisibilityPolicy,
    default_label_provider,
    default_symbol_provider,
    generate_drawing_set,
    generate_elevation,
    generate_plan,
    generate_schedules,
    generate_section,
)
from .model import (
    OUTPUT_VERSION,
    Bounds2,
    DrawingDimension,
    DrawingPrimitive,
    DrawingSchedule,
    DrawingSet,
    DrawingView,
    LineStyle,
    Point2,
    ScheduleColumn,
    ScheduleRow,
    SourceProvenance,
    SourceReference,
)
from .projection import ProjectionFrame, clip_polygon, clip_polyline, clip_segment, frame_from_view_direction
from .svg import view_to_svg

__all__ = [
    "OUTPUT_VERSION",
    "Bounds2",
    "DrawingDimension",
    "DrawingPrimitive",
    "DrawingSchedule",
    "DrawingSet",
    "DrawingView",
    "ElevationSpec",
    "LabelProvider",
    "LineStyle",
    "PlanSpec",
    "Point2",
    "ProjectionFrame",
    "ScheduleColumn",
    "ScheduleRow",
    "SectionSpec",
    "SourceProvenance",
    "SourceReference",
    "Symbol",
    "SymbolProvider",
    "VisibilityPolicy",
    "clip_polygon",
    "clip_polyline",
    "clip_segment",
    "default_label_provider",
    "default_symbol_provider",
    "frame_from_view_direction",
    "generate_drawing_set",
    "generate_elevation",
    "generate_plan",
    "generate_schedules",
    "generate_section",
    "view_to_svg",
]
